smingle/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import VideoResource
from . import views

video_resource = VideoResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('uploads/', include('uploads.urls')),
    path('api/', include(video_resource.urls))
]

uploads/urls.py
from django.urls import path
from . import views

app_name = 'uploads'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:upload_id>', views.detail, name='detail')
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from uploads.models import Video

class VideoResource(ModelResource):
    class Meta:
        queryset = Video.objects.all()
        resource_name = 'uploads'
    

uploads/models.py
from django.db import models
from django.utils import timezone

class AddVid(models.Model):
    vid_type = models.CharField(max_length=220)

    def __str__(self):
        return self.vid_type

class Video(models.Model):
    vid_name = models.CharField(max_length=220)
    video_type = models.ForeignKey(AddVid, on_delete=models.CASCADE)
    date_uploaded = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

smingle/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html') 

uploads/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Video


def index(request):
    videos = Video.objects.all()
    return render(request, 'uploads/index.html', { 'videos': videos })
    
def detail(request, upload_id):
    video = get_object_or_404(Video, id=upload_id)
    return render(request, 'uploads/detail.html', { 'video': video})

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Smingle</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">Smingle</a>
    </nav>
    <main class='container'>
    {% block content %}
    {% endblock  %}
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<a href='{% url 'uploads:index' %}'></a>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">SMingle</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Options
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'uploads:index' %}">Uploads</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% endblock  %}

uploads/templates/uploads/detail.html
{% extends 'base.html' %}
{% block content %}
    <dl>
        <dt>Video Name</dt>
        <dd>{{ upload.vid_name }}</dd>
        <dt>Video Type</dt>
        <dd>{{ upload.video_type }}</dd>
        <dt>Date Created</dt>
        <dd>{{ upload.date_uploaded }}</dd>
    </dl>
{% endblock  %}

uploads/templates/uploads/index.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Video Name</th>
                <th>Video Type</th>
                <th>Date Uploaded</th>
            </tr>
        </thead>
        <rbody>
            {% for video in videos %}
                <tr>
                    <td>
                    <a href='{% url 'uploads:detail' video.id %}'>{{ video.vid_name }}</a>
                    </td>
                    <td>{{ video.video_type }}</td>
                    <td>{{ video.date_uploaded }}</td>
                </tr>
            {% endfor %}
        </rbody>
    </table>
{% endblock  %}